config/routes.rb
TestKoombea::Application.routes.draw do

  devise_for :users
  root :to => "posts#index"
  resources :posts do
    resources :urls
  end
  
end

app/models/content.rb
class Content < ActiveRecord::Base
  
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :message => 'pleace is require'
  validates_presence_of :content, :message => 'pleace is required'
  
  has_many :urls #, :inverse_of => :posts
  accepts_nested_attributes_for :urls
  
  extend FriendlyId
  friendly_id :title, :use => :slugged 
end

app/models/tiny_print.rb
class TinyPrint < ActiveRecord::Base
  
  has_attached_file :image,
    :convert_options => { :quality =>  4 },
    :styles => { :small_thumb => [ "50x50", :jpg ],
	               :medium_thumb => [ "100x100", :jpg ],
                 :large_thumb => [ "370x370", :jpg ],
	               :detail_preview => [ "450x338", :jpg ] },
    #:path => "/prints/:id/:style.:extension",
    :default_url => "/images/missing/prints/:style.png"

end

app/models/tiny_video.rb
class TinyVideo < ActiveRecord::Base
  
  has_attached_file :original
  #, :path => "videos/:original/:id.:extension",

end

app/models/url.rb
class Url < ActiveRecord::Base
  #valido la presencia de un padre
  belongs_to :posts#, :inverse_of => :urls
  validates_format_of :link#, :with => /(http):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/
end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => :create

  def manage
    @attachments = "tiny_#{params[:media]}".classify.constantize.paginate :page => params[:page], :order => 'created_at DESC', :per_page => 10
    render :update do |page|
      page.replace_html :dynamic_images_list, :partial => 'show_attachment_list'
    end
  end
  


  def create
    @attachment = "tiny_#{params[:media]}".classify.constantize.new params[params[:media]]
    
    if @attachment.save
      GC.start
      responds_to_parent do
        render :update do |page|
          page << "upload_callback();"
        end
      end
    else
      responds_to_parent do
        render :update do |page|
          page.alert('Sorry, there was an error uploading the photo.')
        end
      end
    end
  end
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  
  def index
    @content = Content.all
  end

end

app/controllers/link_controller.rb
class LinkController < ApplicationController
  def create
      @post = Post.find(params[:post_id])
      @link = @post.comments.create(params[:comment])
      redirect_to post_path(@post)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  #devise
  before_filter :authenticate_user!
  #uses_tiny_mce :only => [:new, :edit]
  uses_tiny_mce :only => [:new, :edit]
  
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    @post.urls.build
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])
    
    respond_to do |format|
      if @post.save   
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end #fin respond_to
  end

  
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

#Post.create! :title => "content"

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def create
    # @post = Post.find(params[:post_id])
    #     @url = @post.urls.create(params[:url])
    #     if @url.save
    #       redirect_to(@post, :notice => 'URL was successfully add.')
    #     else
    #       redirect_to(@post, :notice => 'The URL, was not added, please rectify.')
    #     end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/link_helper.rb
module LinkHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/remote_link_renderer.rb
class RemoteLinkRenderer < WillPaginate::LinkRenderer
  def page_link_or_span(page, span_class = 'current', text = nil)
    text ||= page.to_s
    if page and page != current_page
      @template.link_to_remote text, :url => url_for(page), :method => :get
    else
      @template.content_tag :span, text, :class => span_class
    end
  end
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/attachments/_show_attachment_list.html.erb
<% unless @attachments.empty? %>
<ul class="attachment_list">
<% @attachments.each do |p| %>
<li id="<%= p.id %>" class="attachment_list">
   <%if params[ :media ] == 'print'%> 
	<div class="thumbs">
    Insert:
		    <br/>
		    <%= link_to "Detail", p.image.url( :detail_preview ), :onclick => "select_thumb(this);return false;"%>
		    <br/>
		    <%= link_to "Large", p.image.url( :large_thumb ), :onclick => "select_thumb(this);return false;"%>
		    <br/>
		    <%= link_to "medium", p.image.url( :medium_thumb ), :onclick => "select_thumb(this);return false;"%>
		    <br/>
		    <%= link_to "Small", p.image.url( :small_thumb ), :onclick => "select_thumb(this);return false;"%>
		    <br/>
		    <%#= link_to 'Delete', delete_attachments_path(@channel.brand_name, params[:feature], :id => p.id, :media => 'print' ), :onclick => "delete_attachment(this);"%>
		    <br/>
		    <%= link_to 'Cancel', 'javascript:void(0)', :onclick => "cancel_image();return false;"%>
	  </div>
	    <%= link_to_function( image_tag( p.image.url( :small_thumb ), :alt => p.image.name ), "select_image(this)" )%>
    <% else%>
	    <%= link_to p.original_file_name, p.original.url, :onclick => "select_thumb(this);return false;"%>&nbsp;&nbsp;&nbsp;
    <% end%>
</li>
<% end %>
</ul>
<br style="clear:both;" />
<div style="float:right;margin-bottom:10px;">
<%= will_paginate @attachments, :class => "pagination", :previous_label => "&laquo; previous",  :next_label => "next &raquo;", :renderer => 'RemoteLinkRenderer' %>
</div>
<% else %>
No <%= params[ :media ]%> Uploaded Yet.
<% end %>

app/views/content/index.html.haml
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>index.html</title>
	<meta name="generator" content="TextMate http://macromates.com/">
	<meta name="author" content="fidel villero">
	<!-- Date: 2011-09-15 -->
</head>
<body>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>De Tolú SUCRE   Fidel José Villero De Hoyos</title>
<link href="/stylesheets/style.css" rel="stylesheet" type="text/css" media="screen" />
<%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= include_tiny_mce_if_needed %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="wrapper">
	<div id="menu">
		<ul>
			<li class="current_page_item"><a href="#">Home</a></li>
			<li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li> 
			<li><a href="#">Blog</a></li>
			<li><a href="#">Photos</a></li>
			<li><a href="#">About</a></li>
			<li><a href="#">Contact</a></li>
		</ul>
		
	</div>
	<!-- end #menu -->
	<div id="header">
		<div id="logo">
			<h1><a href="#">De Tolú SUCRE.</a></h1>
			<h1><p> Fidel José <a href="#">Villero De Hoyos.</a></p></h1>
			
		</div>
	</div>
	<!-- end #header -->
	<div id="page">
	<div id="page-bgtop">
	<div id="page-bgbtm">
		<div id="content">
			
			<%=yield%>
			
			
			
		<div style="clear: both;">&nbsp;</div>
		</div>
		<!-- end #content -->
		<div id="sidebar">
			<ul>
				<li>
					<div id="search" >
					<form method="get" action="#">
						<div>
							<input type="text" name="s" id="search-text" value="" />
							<input type="submit" id="search-submit" value="" />
						</div>
					</form>
					</div>
					<div style="clear: both;">&nbsp;</div>
				</li>
				<li>
					<h2>Aliquam tempus</h2>
					<p>Mauris vitae nisl nec metus placerat perdiet est. Phasellus dapibus semper consectetuer hendrerit.</p>
				</li>
				<li>
					<h2>Categories</h2>
					<ul>
						<li><a href="#">Aliquam libero</a></li>
						<li><a href="#">Consectetuer adipiscing elit</a></li>
						<li><a href="#">Metus aliquam pellentesque</a></li>
						<li><a href="#">Suspendisse iaculis mauris</a></li>
						<li><a href="#">Urnanet non molestie semper</a></li>
						<li><a href="#">Proin gravida orci porttitor</a></li>
					</ul>
				</li>
				<li>
					<h2>Blogroll</h2>
					<ul>
						<li><a href="#">Aliquam libero</a></li>
						<li><a href="#">Consectetuer adipiscing elit</a></li>
						<li><a href="#">Metus aliquam pellentesque</a></li>
						<li><a href="#">Suspendisse iaculis mauris</a></li>
						<li><a href="#">Urnanet non molestie semper</a></li>
						<li><a href="#">Proin gravida orci porttitor</a></li>
					</ul>
				</li>
				<li>
					<h2>Archives</h2>
					<ul>
						<li><a href="#">Aliquam libero</a></li>
						<li><a href="#">Consectetuer adipiscing elit</a></li>
						<li><a href="#">Metus aliquam pellentesque</a></li>
						<li><a href="#">Suspendisse iaculis mauris</a></li>
						<li><a href="#">Urnanet non molestie semper</a></li>
						<li><a href="#">Proin gravida orci porttitor</a></li>
					</ul>
				</li>
			</ul>
		</div>
		<!-- end #sidebar -->
		<div style="clear: both;">&nbsp;</div>
	</div>
	</div>
	</div>
	<!-- end #page -->
</div>
	<div id="footer">
		<p>Copyright (c) 2011 Sitename.com. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
	</div>
	<!-- end #footer -->
</body>
</html>

app/views/link/_form_links.html.erb
<%= form_for(@links) do |f| %>
  <% if @links.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@links.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @links.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
  
<% end %>

app/views/posts/_form.html.erb
<script>
	var count = $("#padre input").size();

  var i = 0;
  function addUrl(){
	var countInput = $('input.new_textField').size();

    var input = $("<input>")//funcion UI de jQuery
    input.attr({
      type: "text",
      name: "post[urls_attributes]["+countInput+"][link]",
      id: "",
      value: "",
      class: "new_textField"
    })
    $("#padre").append(input)
  }

</script>

<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :class => "mceEditor" %>
  </div>
  <!-- 19-09-2011 -->
   <div id="padre">	
      <%= button_to_function "add Url", "addUrl()", :class => "" %>
  </div>
  
  <!-- 19-09-2011 -->
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


<% @posts.each do |post| %>
  <tr>
	<div class="post">
    <h2 class="title"><a href="#"><%= link_to post.title, post %></a></h2>
    <!--<td><%= h raw(post.content) %></td> -->
    <!-- <td><%= post.url %></td> -->
    <%= link_to 'Show', post %>
    <%= link_to 'Edit', edit_post_path(post) %>
    <%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %>
	</div>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<p>
	<div class="post">
		<h2 class="title"><a href="#"><%= @post.title %></a></h2>	
	</div>
</p>

<p>
	<div class="entry">
		<p>
	  		<b><%=h raw(@post.content) %></b>
		</p>
	</div>
</p>

  <b>related links</b>
  <ul>
  <%- @post.urls.each do |url|  %>
  <%- if url.link.index("http://0.0.0.0:3000/").nil?  %>
  	<li>
		<%= link_to(url.link, url.link, html_options = {'target' => "_blank"}) %>
	</li>
    <%-elsif %>
    <li>
		<%= link_to url.link, url.link %>
	</li>
    <%- end%>
  <%- end %>
  </ul>

<%= form_for([@post, @post.urls.build]) do |f| %>

<%- end -%>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>